/*
 * Copyright (c) 2015 All Rights Reserved.
 */
package com.haiziyouke.db.model;
import java.io.Serializable;
// auto generated imports

/**
 * A data object class directly models database table <tt>edu_third_login</tt>.
 *
 * This file is generated by <tt>maven-mybatisdalgen-plugin</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>mybatis</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/(bundle-name)-dal/src/main/resources/META-INF/tables</tt>, and 
 * find the corresponding configuration file (<tt>tables/edu_third_login.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>mvn mydalgen:mybatis</tt> 
 * to generate this file.
 *
 * @author zhengjunweimail@163.com
 */
public class ThirdLoginDO implements Serializable{
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.
	 */
	private Integer id;


	/**
	 * This property corresponds to db column <tt>userId</tt>.
	 */
	private String userId;


	/**
	 * This property corresponds to db column <tt>openId</tt>.
	 */
	private String openId;


	/**
	 * This property corresponds to db column <tt>openMethod</tt>.
	 */
	private String openMethod;


	/**
	 * This property corresponds to db column <tt>unionId</tt>.
	 */
	private String unionId;


	/**
	 * This property corresponds to db column <tt>publicOpenId</tt>.
	 */
	private String publicOpenId;


	/**
	 * This property corresponds to db column <tt>deleted</tt>.
	 */
	private Boolean deleted;


    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public Integer getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(Integer id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>openId</tt>.
     *
     * @return property value of openId
     */
	public String getOpenId() {
		return openId;
	}
	
	/**
	 * Setter method for property <tt>openId</tt>.
	 * 
	 * @param openId value to be assigned to property openId
     */
	public void setOpenId(String openId) {
		this.openId = openId;
	}

    /**
     * Getter method for property <tt>openMethod</tt>.
     *
     * @return property value of openMethod
     */
	public String getOpenMethod() {
		return openMethod;
	}
	
	/**
	 * Setter method for property <tt>openMethod</tt>.
	 * 
	 * @param openMethod value to be assigned to property openMethod
     */
	public void setOpenMethod(String openMethod) {
		this.openMethod = openMethod;
	}

    /**
     * Getter method for property <tt>unionId</tt>.
     *
     * @return property value of unionId
     */
	public String getUnionId() {
		return unionId;
	}
	
	/**
	 * Setter method for property <tt>unionId</tt>.
	 * 
	 * @param unionId value to be assigned to property unionId
     */
	public void setUnionId(String unionId) {
		this.unionId = unionId;
	}

    /**
     * Getter method for property <tt>publicOpenId</tt>.
     *
     * @return property value of publicOpenId
     */
	public String getPublicOpenId() {
		return publicOpenId;
	}
	
	/**
	 * Setter method for property <tt>publicOpenId</tt>.
	 * 
	 * @param publicOpenId value to be assigned to property publicOpenId
     */
	public void setPublicOpenId(String publicOpenId) {
		this.publicOpenId = publicOpenId;
	}

    /**
     * Getter method for property <tt>deleted</tt>.
     *
     * @return property value of deleted
     */
	public Boolean getDeleted() {
		return deleted;
	}
	
	/**
	 * Setter method for property <tt>deleted</tt>.
	 * 
	 * @param deleted value to be assigned to property deleted
     */
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}
}
