package com.haiziyouke.db.model;

import java.io.Serializable;
import java.util.Date;


/**
 * A data object class directly models database table <tt>edu_user</tt>.
 *
 * This file is generated by <tt>maven-mybatisdalgen-plugin</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>mybatis</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/(bundle-name)-dal/src/main/resources/META-INF/tables</tt>, and 
 * find the corresponding configuration file (<tt>tables/edu_user.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>mvn mydalgen:mybatis</tt> 
 * to generate this file.
 *
 * @author zhengjunweimail@163.com
 */
public class UserDO implements Serializable{

    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>userId</tt>.
	 */
	private String userId;


	/**
	 * This property corresponds to db column <tt>nickName</tt>.
	 */
	private String nickName;


	/**
	 * This property corresponds to db column <tt>sexCode</tt>.
	 */
	private Integer sexCode;


	/**
	 * This property corresponds to db column <tt>phone</tt>.
	 */
	private String phone;


	/**
	 * This property corresponds to db column <tt>image</tt>.
	 */
	private String image;


	/**
	 * This property corresponds to db column <tt>clientId</tt>.
	 */
	private String clientId;


	/**
	 * This property corresponds to db column <tt>birthday</tt>.
	 */
	private String birthday;


	/**
	 * This property corresponds to db column <tt>realName</tt>.
	 */
	private String realName;


	/**
	 * This property corresponds to db column <tt>createTime</tt>.
	 */
	private Date createTime;


	/**
	 * This property corresponds to db column <tt>modifyTime</tt>.
	 */
	private Date modifyTime;


	/**
	 * This property corresponds to db column <tt>deleted</tt>.
	 */
	private Boolean deleted;


	/**
	 * This property corresponds to db column <tt>identity</tt>.
	 */
	private Integer identity;


	/**
	 * This property corresponds to db column <tt>intr</tt>.
	 */
	private String intr;


	/**
	 * This property corresponds to db column <tt>rank</tt>.
	 */
	private String rank;


    //========== getters and setters ==========

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>nickName</tt>.
     *
     * @return property value of nickName
     */
	public String getNickName() {
		return nickName;
	}
	
	/**
	 * Setter method for property <tt>nickName</tt>.
	 * 
	 * @param nickName value to be assigned to property nickName
     */
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

    /**
     * Getter method for property <tt>sexCode</tt>.
     *
     * @return property value of sexCode
     */
	public Integer getSexCode() {
		return sexCode;
	}
	
	/**
	 * Setter method for property <tt>sexCode</tt>.
	 * 
	 * @param sexCode value to be assigned to property sexCode
     */
	public void setSexCode(Integer sexCode) {
		this.sexCode = sexCode;
	}

    /**
     * Getter method for property <tt>phone</tt>.
     *
     * @return property value of phone
     */
	public String getPhone() {
		return phone;
	}
	
	/**
	 * Setter method for property <tt>phone</tt>.
	 * 
	 * @param phone value to be assigned to property phone
     */
	public void setPhone(String phone) {
		this.phone = phone;
	}

    /**
     * Getter method for property <tt>image</tt>.
     *
     * @return property value of image
     */
	public String getImage() {
		return image;
	}
	
	/**
	 * Setter method for property <tt>image</tt>.
	 * 
	 * @param image value to be assigned to property image
     */
	public void setImage(String image) {
		this.image = image;
	}

    /**
     * Getter method for property <tt>clientId</tt>.
     *
     * @return property value of clientId
     */
	public String getClientId() {
		return clientId;
	}
	
	/**
	 * Setter method for property <tt>clientId</tt>.
	 * 
	 * @param clientId value to be assigned to property clientId
     */
	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

    /**
     * Getter method for property <tt>birthday</tt>.
     *
     * @return property value of birthday
     */
	public String getBirthday() {
		return birthday;
	}
	
	/**
	 * Setter method for property <tt>birthday</tt>.
	 * 
	 * @param birthday value to be assigned to property birthday
     */
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

    /**
     * Getter method for property <tt>realName</tt>.
     *
     * @return property value of realName
     */
	public String getRealName() {
		return realName;
	}
	
	/**
	 * Setter method for property <tt>realName</tt>.
	 * 
	 * @param realName value to be assigned to property realName
     */
	public void setRealName(String realName) {
		this.realName = realName;
	}

    /**
     * Getter method for property <tt>createTime</tt>.
     *
     * @return property value of createTime
     */
	public Date getCreateTime() {
		return createTime;
	}
	
	/**
	 * Setter method for property <tt>createTime</tt>.
	 * 
	 * @param createTime value to be assigned to property createTime
     */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

    /**
     * Getter method for property <tt>modifyTime</tt>.
     *
     * @return property value of modifyTime
     */
	public Date getModifyTime() {
		return modifyTime;
	}
	
	/**
	 * Setter method for property <tt>modifyTime</tt>.
	 * 
	 * @param modifyTime value to be assigned to property modifyTime
     */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

    /**
     * Getter method for property <tt>deleted</tt>.
     *
     * @return property value of deleted
     */
	public Boolean getDeleted() {
		return deleted;
	}
	
	/**
	 * Setter method for property <tt>deleted</tt>.
	 * 
	 * @param deleted value to be assigned to property deleted
     */
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

    /**
     * Getter method for property <tt>identity</tt>.
     *
     * @return property value of identity
     */
	public Integer getIdentity() {
		return identity;
	}
	
	/**
	 * Setter method for property <tt>identity</tt>.
	 * 
	 * @param identity value to be assigned to property identity
     */
	public void setIdentity(Integer identity) {
		this.identity = identity;
	}

    /**
     * Getter method for property <tt>intr</tt>.
     *
     * @return property value of intr
     */
	public String getIntr() {
		return intr;
	}
	
	/**
	 * Setter method for property <tt>intr</tt>.
	 * 
	 * @param intr value to be assigned to property intr
     */
	public void setIntr(String intr) {
		this.intr = intr;
	}

    /**
     * Getter method for property <tt>rank</tt>.
     *
     * @return property value of rank
     */
	public String getRank() {
		return rank;
	}
	
	/**
	 * Setter method for property <tt>rank</tt>.
	 * 
	 * @param rank value to be assigned to property rank
     */
	public void setRank(String rank) {
		this.rank = rank;
	}
}
